
package com.vku.GUI;

import com.vku.DAO.TaiKhoanDAO;
import com.vku.MODEL.DN_ChuModel;
import com.vku.MODEL.Taikhoan;
import javax.swing.JOptionPane;
import com.vku.Connect.Connect;
/**
 *
 * @author kinhn
 */
public class DK_TK extends javax.swing.JFrame {

    /**
     * Creates new form DK_TK
     */
Connect cn = new Connect();
    public DK_TK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        nhanVienBtn = new javax.swing.JCheckBox();
        chuBtn = new javax.swing.JCheckBox();
        txtUserName = new javax.swing.JTextField();
        txtPassWord = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        smk = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vku/icon/back.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 70, 60));

        nhanVienBtn.setText("nhân viên");
        getContentPane().add(nhanVienBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, -1));

        chuBtn.setText("Chủ");
        getContentPane().add(chuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 330, 50));
        getContentPane().add(txtPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 320, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Đăng ký");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 270, 60));

        smk.setText("Hiển thị mật khẩu");
        smk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smkActionPerformed(evt);
            }
        });
        getContentPane().add(smk, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Đăng ký");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 450, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Tên tài khoản");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Mật khẩu");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vku/icon/DACS.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String user, pass;
        user = txtUserName.getText();
        pass = txtPassWord.getText(); 
        Taikhoan tk = new Taikhoan();
        tk.SetUsername(user);
        tk.SetPassword(pass);
        //chọn cả 2
        if (chuBtn.isSelected() && nhanVienBtn.isSelected()){
JOptionPane.showMessageDialog(rootPane, "Chỉ chọn chủ hoặc nhân viên", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        boolean check = false;
        if(check == true){
    JOptionPane.showMessageDialog(rootPane, "Đăng ký thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        TC_Chu tc = new TC_Chu();
        tc.show();
        dispose();
        }
        }
//        chọn chủ 
        else if (chuBtn.isSelected()){
            tk.SetLv(1);
            boolean check = cn.themTk(tk);
            if(check == true){
    JOptionPane.showMessageDialog(rootPane, "Đăng ký thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        TC_Chu tc = new TC_Chu();
        tc.show();
        dispose();
        }
        }
        // chọn  nv
        else if (nhanVienBtn.isSelected()){
            tk.SetLv(2);
            boolean check = cn.themTk(tk);
            if(check == true){
    JOptionPane.showMessageDialog(rootPane, "Đăng ký thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        TC_Chu tc = new TC_Chu();
        tc.show();
        dispose();
        }
        }
        else{
 JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn chủ hoặc nhân viên", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void smkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smkActionPerformed
        if(smk.isSelected()){
            txtPassWord.setEchoChar((char)0);
        }
        else {
            txtPassWord.setEchoChar('*');
        }
    }//GEN-LAST:event_smkActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TC_Chu tc = new TC_Chu();
        tc.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DK_TK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DK_TK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DK_TK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DK_TK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DK_TK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chuBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox nhanVienBtn;
    private javax.swing.JCheckBox smk;
    private javax.swing.JPasswordField txtPassWord;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
